package studio.vibe.shared.model

import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

public enum class SpecStatus {
    UNKNOWN,
    PASSING,
    FAILING,
}

@OptIn(ExperimentalUuidApi::class)
public data class SpecFile(
    val id: Uuid = Uuid.random(),
    val path: FilePath,
    val name: String = path.path
        .substringAfterLast('/')
        .removeSuffix(".md")
        .removeSuffix(".cs"),
    val status: SpecStatus = SpecStatus.UNKNOWN,
    val passCount: Int = 0,
    val totalCount: Int = 0,
)

public data class SpecStats(
    val passing: Int,
    val total: Int,
    val buildDate: Instant,
) {
    public val allPassing: Boolean get() = total > 0 && passing == total
    public val failing: Int get() = total - passing
}

public enum class CodeSpeakCommand(public val id: String) {
    BUILD("build"),
    RUN("run"),
    IMPL("impl"),
    TEST("test"),
    TASK("task"),
    CHANGE("change");

    public val displayName: String
        get() = when (this) {
            BUILD -> "Build"
            RUN -> "Run"
            IMPL -> "Impl"
            TEST -> "Test"
            TASK -> "Task"
            CHANGE -> "Change"
        }

    public val requiresInput: Boolean
        get() = this == TASK || this == CHANGE

    public val inputLabel: String
        get() = when (this) {
            TASK -> "Task"
            CHANGE -> "Message"
            else -> ""
        }

    public val inputPlaceholder: String
        get() = when (this) {
            TASK -> "Task name..."
            CHANGE -> "Describe the change..."
            else -> ""
        }

    public val supportsStatsParsing: Boolean
        get() = this == BUILD

    public fun cliArguments(
        specPath: String? = null,
        taskName: String = "",
        changeMessage: String = "",
    ): List<String> = when (this) {
        TASK -> {
            val sanitizedTask = taskName.take(256)
            buildList {
                add("task")
                add("--no-interactive")
                add("--")
                add(sanitizedTask)
                specPath?.let { addAll(listOf("--spec", it)) }
            }
        }
        CHANGE -> {
            val sanitizedMessage = changeMessage.take(2000)
            buildList {
                add("change")
                add("--no-interactive")
                specPath?.let { add(it) }
                addAll(listOf("-m", sanitizedMessage))
            }
        }
        else -> buildList {
            add(id)
            add("--no-interactive")
            specPath?.let { add(it) }
        }
    }
}

public data class CodeSpeakRunBarState(
    val command: CodeSpeakCommand = CodeSpeakCommand.BUILD,
    val taskName: String = "",
    val changeMessage: String = "",
    val isRunning: Boolean = false,
    val stopRequested: Boolean = false,
    val currentSpecName: String = "",
    val isEditorDirty: Boolean = false,
)

public object GeneratedFileDetector {
    public val markerPrefixes: List<String> = listOf(
        "<!-- generated by codespeak",
        "// generated by codespeak",
        "# generated by codespeak",
        "/* generated by codespeak",
    )

    public fun isGenerated(contents: String): Boolean {
        val lines = contents.lineSequence().take(3)
        return lines.any { line ->
            val lower = line.lowercase()
            markerPrefixes.any { lower.startsWith(it) }
        }
    }

    public fun parseSpecName(contents: String): String {
        val keyword = "from spec file:"
        for (line in contents.lineSequence().take(3)) {
            val lower = line.lowercase()
            val idx = lower.indexOf(keyword)
            if (idx >= 0) {
                return line.substring(idx + keyword.length)
                    .trim()
                    .split(" ")
                    .firstOrNull()
                    .orEmpty()
            }
        }
        return ""
    }
}

@OptIn(ExperimentalUuidApi::class)
public data class GeneratedFile(
    val id: Uuid = Uuid.random(),
    val path: FilePath,
    val specName: String = "",
) {
    public val name: String get() = path.name
}
