// MARK: - GeneratedFile
// Model for a file generated by CodeSpeak from a .cs.md spec.
// macOS 14+, Swift 5.10

import Foundation

/// A source file produced by `codespeak build`.
///
/// Detection: presence of a CodeSpeak marker in the first 3 lines.
/// Supported marker prefixes:
/// - `<!-- Generated by CodeSpeak`  (HTML/XML)
/// - `// Generated by CodeSpeak`    (Swift/JS/TS/CSS)
/// - `# Generated by CodeSpeak`     (Python/Shell/YAML)
/// - `/* Generated by CodeSpeak`    (C/Java/CSS block)
struct GeneratedFile: Identifiable, Hashable {
    let id: UUID
    let url: URL

    /// Last path component of `url`.
    var name: String { url.lastPathComponent }

    /// Spec name parsed from "from spec file: …" in the marker line,
    /// or empty string if the line doesn't contain that phrase.
    var specName: String

    // MARK: - Marker Detection

    /// Marker search strings (lowercased for case-insensitive match).
    static let markerPrefixes: [String] = [
        "<!-- generated by codespeak",
        "// generated by codespeak",
        "# generated by codespeak",
        "/* generated by codespeak",
    ]

    /// Returns true if the first 3 lines of `contents` contain a CodeSpeak marker.
    static func isGenerated(_ contents: String) -> Bool {
        let lines = contents
            .components(separatedBy: .newlines)
            .prefix(3)
        for line in lines {
            let lower = line.lowercased()
            for prefix in markerPrefixes where lower.hasPrefix(prefix) {
                return true
            }
        }
        return false
    }

    /// Parses the spec name from a marker line like
    /// `<!-- Generated by CodeSpeak from spec file: spec/auth.cs.md -->`.
    static func parseSpecName(from contents: String) -> String {
        let lines = contents
            .components(separatedBy: .newlines)
            .prefix(3)
        let keyword = "from spec file:"
        for line in lines {
            let lower = line.lowercased()
            guard let range = lower.range(of: keyword) else { continue }
            let after = String(line[range.upperBound...])
                .trimmingCharacters(in: .whitespaces)
                // Strip trailing HTML/block-comment closers
                .components(separatedBy: .whitespaces).first ?? ""
            return after
        }
        return ""
    }
}
