package studio.vibe.shared.feature.codespeak.domain

import studio.vibe.shared.core.common.GeneratedFileDetecting

public object GeneratedFileDetector : GeneratedFileDetecting {
    public val markerPrefixes: List<String> = listOf(
        "<!-- generated by codespeak",
        "// generated by codespeak",
        "# generated by codespeak",
        "/* generated by codespeak",
    )

    override fun isGenerated(contents: String): Boolean {
        val lines = contents.lineSequence().take(3)
        return lines.any { line ->
            val lower = line.lowercase()
            markerPrefixes.any { lower.startsWith(it) }
        }
    }

    override fun parseSpecName(contents: String): String {
        val keyword = "from spec file:"
        for (line in contents.lineSequence().take(3)) {
            val lower = line.lowercase()
            val idx = lower.indexOf(keyword)
            if (idx >= 0) {
                return line.substring(idx + keyword.length)
                    .trim()
                    .split(" ")
                    .firstOrNull()
                    .orEmpty()
            }
        }
        return ""
    }
}
